name = "anotherbeachproject"
account_id = "9aea46551a6124e9e4d0233168e81f47"
compatibility_date = "2026-05-01"
main = "src/worker.js"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[vars]
SUPABASE_URL = "https://xccpopnwqrxjjhrtyiwd.supabase.co"

[env.dev]
name = "anotherbeachproject-dev"

[env.dev.assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[env.dev.vars]
SUPABASE_URL = "https://esxnberopfmfaebmbqwd.supabase.co"
